import { expect, test } from '@playwright/test'
import {
  editorLine,
  expectCleanBrowser,
  expectIsolatedRuntime,
  observeBrowserDiagnostics,
} from './browser-test-helpers'

test('runs and debugs C++ with the production runtime', async ({ page }) => {
  const diagnostics = observeBrowserDiagnostics(page)
  const navigation = await page.goto('/?runtime=cpp')

  await expectIsolatedRuntime(page, navigation)

  const statusBar = page.getByRole('contentinfo', { name: 'Status bar' })
  const terminal = page.locator('.xterm-rows')
  const runCommand = page.locator('[data-command-id="workbench.run"]')
  const debugCommand = page.locator('[data-command-id="workbench.debug"]')

  await expect(page.locator('.monaco-editor')).toBeVisible()
  await expect(statusBar).toContainText('Ready')
  await expect(runCommand).toBeVisible()
  await expect(debugCommand).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Variables', exact: true })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Graph', exact: true })).toBeVisible()

  await runCommand.click()
  await expect(terminal).toContainText('Double 5 is 10')
  await expect(terminal).toContainText('Program exited with code 0')
  await expect(statusBar).toContainText('Ready')

  const seedLine = editorLine(page, 'int seed = 5;')
  await expect(seedLine).toHaveCount(1)
  await seedLine.click()
  await page.keyboard.press('F9')
  await expect(page.locator('.monaco-editor .breakpoint-dot')).toHaveCount(1)

  await debugCommand.click()
  await expect(statusBar).toContainText('Paused at main.cpp:9')
  await expect(page.getByRole('toolbar', { name: 'Debug controls' })).toBeVisible()

  // debugger-sh 0.3.15 cannot remove native breakpoints from a live C++
  // session. Web IDE must reject the edit and restore the authoritative dot.
  await seedLine.click()
  await page.keyboard.press('F9')
  await expect(terminal).toContainText('Stop the current debug session before changing breakpoints')
  await expect(page.locator('.monaco-editor .breakpoint-dot')).toHaveCount(1)

  await page.getByRole('button', { name: 'Step Over', exact: true }).click()
  await expect(statusBar).toContainText('Paused at main.cpp:10')
  const locals = page.getByText('Locals', { exact: true }).locator('..')
  await expect(locals).toContainText('seed')
  await expect(locals).toContainText('5')

  await page.getByRole('button', { name: 'Step Into', exact: true }).click()
  await expect(statusBar).toContainText('Paused at main.cpp:4')
  await expect(locals).toContainText('value')
  await expect(locals).toContainText('5')

  await page.getByRole('button', { name: 'Step Over', exact: true }).click()
  await expect(statusBar).toContainText('Paused at main.cpp:5')
  await expect(locals).toContainText('result')
  await expect(locals).toContainText('10')

  await page.getByRole('button', { name: 'Step Out', exact: true }).click()
  await expect(statusBar).toContainText('Paused at main.cpp:11')
  await expect(locals).toContainText('answer')
  await expect(locals).toContainText('10')

  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(statusBar).toContainText('Ready')
  await expect(page.getByRole('toolbar', { name: 'Debug controls' })).toHaveCount(0)

  expectCleanBrowser(diagnostics)
})

test('discovers, runs, and debugs selected C++ tests using the production framework', async ({ page }) => {
  const diagnostics = observeBrowserDiagnostics(page)
  await page.goto('/?runtime=cpp&tests=framework')
  const status = page.getByRole('contentinfo', { name: 'Status bar' })
  await expect(status).toContainText('Ready')
  await page.getByRole('tab', { name: 'Tests', exact: true }).click()
  const panel = page.getByRole('complementary', { name: 'Tests' })
  await expect(panel.getByText('numeric provided', { exact: true })).toBeVisible()
  await expect(panel.getByText('inactive test', { exact: true })).toBeVisible()
  await expect(panel.getByText('runtime macro', { exact: true })).toHaveCount(0)
  await expect(page.locator('.xterm-rows')).not.toContainText('Program exited')
  await panel.getByRole('button', { name: 'Run All', exact: true }).click()
  await expect(panel).toContainText('2 passed · 1 failed · 1 errored')
  await expect(panel.getByText('inactive test', { exact: true })).toHaveCount(0)
  await expect(panel.getByText('runtime macro', { exact: true })).toBeVisible()
  await expect(panel).toContainText('actual 2 = 2')
  await expect(panel).toContainText('expected 3 = 3')
  await expect(panel).toContainText('expected boom')
  await expect(status).toContainText('Ready')
  for (const checkbox of await panel.getByRole('checkbox').all()) await checkbox.uncheck()
  await panel.getByRole('checkbox', { name: 'Select numeric provided', exact: true }).check()
  const line = editorLine(page, 'int result = value * 2;')
  await line.click(); await page.keyboard.press('F9')
  await panel.getByRole('button', { name: 'Debug Selected', exact: true }).click()
  await expect(status).toContainText('Paused at main.cpp:4')
  await page.getByRole('button', { name: 'Restart', exact: true }).click()
  await expect(status).not.toContainText('Paused')
  await expect(status).toContainText('Paused at main.cpp:4')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(panel).toContainText('1 passed · 0 failed · 0 errored')
  await expect(status).toContainText('Ready')
  expectCleanBrowser(diagnostics)
})

test('terminates an infinite C++ test with an explicit execution timeout', async ({ page }) => {
  const diagnostics = observeBrowserDiagnostics(page)
  await page.goto('/?runtime=cpp&tests=timeout')
  await page.getByRole('tab', { name: 'Tests', exact: true }).click()
  const panel = page.getByRole('complementary', { name: 'Tests' })
  await expect(panel.getByText('infinite loop', { exact: true })).toBeVisible()
  await panel.getByRole('button', { name: 'Run All', exact: true }).click()
  await expect(panel).toContainText('Run timeout')
  await expect(panel).toContainText('interrupted')
  await expect(page.getByRole('contentinfo', { name: 'Status bar' })).toContainText('Ready')
  expectCleanBrowser(diagnostics)
})


test('opens changed failure and paused locations in the frozen executed source', async ({ page }) => {
  await page.goto('/?runtime=cpp&tests=framework')
  const status = page.getByRole('contentinfo', { name: 'Status bar' })
  await page.getByRole('tab', { name: 'Tests', exact: true }).click()
  const panel = page.getByRole('complementary', { name: 'Tests' })
  await panel.getByRole('button', { name: 'Run All', exact: true }).click()
  await expect(panel).toContainText('2 passed · 1 failed · 1 errored')
  await expect(status).toContainText('Ready')
  await panel.getByRole('button', { name: /^tests.cpp:/ }).first().click()
  await page.locator('.monaco-editor .view-lines').click()
  const mac = /Macintosh/.test(await page.evaluate(() => navigator.userAgent))
  await page.keyboard.press(mac ? 'Meta+ArrowUp' : 'Control+Home')
  await page.keyboard.insertText('// Edited after the run.\n')
  await expect(panel).toContainText('Stale results')
  await panel.getByRole('button', { name: /^tests.cpp:/ }).first().click()
  let dialog = page.getByRole('dialog', { name: 'Executed source snapshot' })
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText('EXPECT_EQUAL(2, 3)')
  await expect(dialog).not.toContainText('Edited after the run')
  await dialog.getByRole('button', { name: 'Close source snapshot' }).click()
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('Edited after the run')
  await expect(page.locator('.source-presentation-error-line')).toHaveCount(0)
  await expect(panel.getByText('Previous run', { exact: true })).toHaveCount(4)
  await page.getByRole('tab', { name: /main.cpp/ }).click()
  await editorLine(page, 'int result = value * 2;').click(); await page.keyboard.press('F9')
  for (const checkbox of await panel.locator('input[type=checkbox]:enabled').all()) await checkbox.uncheck()
  await panel.locator('input[aria-label="Select numeric provided"]:enabled').check()
  await panel.getByRole('button', { name: 'Debug Selected', exact: true }).click()
  await expect(status).toContainText('Paused at main.cpp:4')
  await editorLine(page, 'int result = value * 2;').click()
  await page.keyboard.press(mac ? 'Meta+ArrowUp' : 'Control+Home')
  await page.keyboard.insertText('// Edited while paused.\n')
  await expect(page.getByRole('button', { name: 'View executed source' })).toBeVisible()
  await expect(page.locator('.debug-line-highlight')).toHaveCount(0)
  await page.getByRole('button', { name: 'View executed source' }).click()
  dialog = page.getByRole('dialog', { name: 'Executed source snapshot' })
  await expect(dialog).toContainText('int result = value * 2;')
  await expect(dialog).not.toContainText('Edited while paused')
  await dialog.getByRole('button', { name: 'Close source snapshot' }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(status).toContainText('Ready')
  await expect(panel).toContainText('1 passed · 0 failed · 0 errored')
  await expect(panel).toContainText('Stale results')
})
